[package]

name = "solidoak"
version = "0.0.1"
authors = ["oakes <zsoakes@gmail.com>"]

[dependencies.rgtk]

path = "../rgtk"
features = ["GTK_3_6"]

[dependencies.neovim-rs]

path = "../neovim-rs"

[dependencies.rustc-serialize]

rustc-serialize = "0.2.10"
