[package]

name = "solidoak"
version = "0.0.1"
authors = ["oakes <zsoakes@gmail.com>"]
build = "build.rs"

[dependencies.rgtk]

git = "https://github.com/oakes/rgtk"
features = ["GTK_3_6"]

[dependencies.neovim-rs]

neovim-rs = "0.0.5"

[dependencies.rustc-serialize]

rustc-serialize = "0.2.*"
