[package]

name = "solidoak"
version = "0.1.0"
authors = ["oakes <zsoakes@gmail.com>"]
build = "build.rs"

[dependencies.rgtk]

git = "https://github.com/oakes/rgtk"
features = ["GTK_3_10"]

[dependencies.neovim-rs]

git = "https://github.com/oakes/neovim-rs"

[dependencies.racer]

git = "https://github.com/oakes/racer"

[dependencies.rustc-serialize]

rustc-serialize = "0.2.*"
