[package]

name = "solidoak"
version = "0.0.1"
authors = ["oakes <zsoakes@gmail.com>"]

[dependencies.rgtk]

git = "https://github.com/jeremyletang/rgtk.git"

# run the following to set the correct GTK version:
# export GTK_VERSION=${GTK_VERSION:=GTK_3_10}
