[package]

name = "solidoak"
version = "0.1.1"
authors = ["oakes <zsoakes@gmail.com>"]
build = "build.rs"

[dependencies.rgtk]

git = "https://github.com/oakes/rgtk.git"
features = ["GTK_3_10"]

[dependencies.neovim-rs]

git = "https://github.com/oakes/neovim-rs.git"

[dependencies.rustc-serialize]

rustc-serialize = "0.3"
